name: WorstShop
version: @version@
main: com.jacky8399.worstshop.WorstShop
api-version: 1.15
depend:
  - Vault
softdepend:
  - PlayerPoints
  - PlaceholderAPI
  - LuckPerms
author: jacky8399
description: The worst shop plugin.

commands:
  worstshop:
    usage: '/<command> [shop]'
    aliases: ['shop']
  sell:
    usage: '/sell <hand/all/container/type>'
  buy:
    usage: '/buy <type> [count]'
