name: WorstShop
version: '${version}'
main: com.jacky8399.worstshop.WorstShop
api-version: 1.17
depend:
  - Vault
softdepend:
  - PlayerPoints
  - PlaceholderAPI
  - LuckPerms
  - QuickShop
author: jacky8399
description: The worst shop plugin.

permissions:
  # Player permissions
  worstshop.player:
    default: true
    children:
      worstshop.command.shop: true # Allows using /shop
      worstshop.command.open: true # Allows using /shop [shop]

  # Admin permissions
  worstshop.*:
    default: op
    children:
      worstshop.command.*: true
      worstshop.shops.*: true

  worstshop.command.*:
    children:
      worstshop.command.sell.*: true
      worstshop.command.buy.*: true
      worstshop.command.shop.*: true
      worstshop.command.shop.discount.*: true
      worstshop.command.log.*: true


commands:
  worstshop:
    usage: '/<command> [shop]'
    aliases: ['shop']
  sell:
    usage: '/sell <hand/all/container/type>'
  buy:
    usage: '/buy <type> [count]'
