name: WorstShop
version: @version@
main: com.jacky8399.worstshop.WorstShop
api-version: 1.16
depend:
  - Vault
softdepend:
  - PlayerPoints
  - PlaceholderAPI
  - LuckPerms
  - QuickShop
author: jacky8399
description: The worst shop plugin.

permissions:
#  worstshop.discount.*:
#    children:
#      worstshop.discount.create: true
#      worstshop.discount.list: true
#      worstshop.discount.delete: true
#
#  worstshop.log.*:
#    children:
#      worstshop.log.error: true
#      worstshop.log.purchases: true

  worstshop.*:
    default: op
    children:
      worstshop.discount.*: true
      worstshop.log.*: true
      worstshop.shops.*: true
      worstshop.shop.*: true

commands:
  worstshop:
    usage: '/<command> [shop]'
    aliases: ['shop']
  sell:
    usage: '/sell <hand/all/container/type>'
  buy:
    usage: '/buy <type> [count]'
